### ISSUE TITLE
ImportError: No module named masscan

### ISSUE THREAD

**Issue by The-legend3** [cheetz/sslScrape#1]
Although I have masscan installed, I get the following error: 
```
root@legendary:~/sslScrape# python sslScrape.py 
Traceback (most recent call last):
  File "sslScrape.py", line 31, in <module>
    import masscan, errno, os, signal
ImportError: No module named masscan
```

**Comment by cheetz** [comment]
Hi The-legend3,

Did you install the requirements listed in the requirements.txt file:

Requirements:
pip install ndg-httpsclient
pip install python-masscan

Let me know if that fixes it.

**Comment by The-legend3** [comment]
Hi cheetz, 

Thanks for your prompt response.

The requirements are already satisfied (see below). 

`root@legendary:~/sslScrape# pip3 install ndg-httpsclient
Requirement already satisfied: ndg-httpsclient in /usr/local/lib/python3.5/dist-packages (0.5.0)
Requirement already satisfied: PyOpenSSL in /usr/local/lib/python3.5/dist-packages (from ndg-httpsclient) (18.0.0)
Requirement already satisfied: pyasn1>=0.1.1 in /usr/lib/python3/dist-packages (from ndg-httpsclient) (0.1.9)
Requirement already satisfied: cryptography>=2.2.1 in /usr/local/lib/python3.5/dist-packages (from PyOpenSSL->ndg-httpsclient) (2.2.2)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.5/dist-packages (from PyOpenSSL->ndg-httpsclient) (1.11.0)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.2.1->PyOpenSSL->ndg-httpsclient) (2.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.2.1->PyOpenSSL->ndg-httpsclient) (0.24.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.2.1->PyOpenSSL->ndg-httpsclient) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.2.1->PyOpenSSL->ndg-httpsclient) (2.18)`

`root@legendary:~/sslScrape# pip3 install python-masscan
Requirement already satisfied: python-masscan in /usr/local/lib/python3.5/dist-packages (0.1.1)`

**Comment by cheetz** [comment]
Might be wrong here, but pip3 is for python3 and this is for python 2.7.  Can you try it just doing pip instead of pip3?

-pk

**Comment by The-legend3** [comment]
PK,

You are right here. Just installed it with pip and it worked fine. Thanks for your help.

**Comment by cheetz** [comment]
Np, hope you are enjoying the book!
